"use client";

import { useState, useEffect } from 'react';
import { useRouter, useParams } from 'next/navigation';
import Link from 'next/link';
import { Course } from '@/types/course';
import { useAuth } from '@/hooks/useAuth';
import { db } from '@/lib/firebase';
import { doc, setDoc, updateDoc, getDoc } from 'firebase/firestore';
import { useData } from '@/providers/DataProvider';
import { jsPDF } from "jspdf";

export default function ModuleViewerPage() {
  const { moduleSlug: rawModuleSlug, courseSlug: rawCourseSlug } = useParams();
  const courseSlug = decodeURIComponent(rawCourseSlug as string);
  const moduleSlug = decodeURIComponent(rawModuleSlug as string);
  const { user } = useAuth();
  const { userData, globalCourses, loading: dataLoading } = useData();
  const [activeCourse, setActiveCourse] = useState<Course | null>(null);
  const [viewingDoc, setViewingDoc] = useState<string | null>(null);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [isCompleted, setIsCompleted] = useState(false);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [courseProgressData, setCourseProgressData] = useState<any>(null);
  const [videoId, setVideoId] = useState<string | null>(null);
  const router = useRouter();

  const loading = dataLoading;

  const buildPDF = (docTitle: string, courseName: string) => {
    const doc = new jsPDF();
    const pageHeight = doc.internal.pageSize.getHeight();
    let y = 20;

    // Title Page
    doc.setFontSize(28);
    doc.setTextColor(30, 64, 175);
    doc.text(docTitle, 20, y);
    y += 20;

    doc.setFontSize(16);
    doc.setTextColor(100, 100, 100);
    doc.text(`Comprehensive Reference Manual for ${courseName}`, 20, y);
    y += 30;

    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text(`Generated by CodeMentor AI`, 20, y);
    y += 20;

    // Table of Contents
    doc.addPage();
    y = 20;
    doc.setFontSize(22);
    doc.setTextColor(0, 0, 0);
    doc.text("Table of Contents", 20, y);
    y += 20;
    
    doc.setFontSize(12);
    for(let i=1; i<=25; i++) {
       doc.text(`${i}. Core Principles and Advanced Applications of ${docTitle.split(' ')[0]}`, 20, y);
       doc.text(`Page ${i + 2}`, 180, y, { align: 'right' });
       y += 10;
    }

    // Generate 25 pages of content
    for (let p = 1; p <= 25; p++) {
      doc.addPage();
      y = 20;
      doc.setFontSize(18);
      doc.setTextColor(30, 64, 175);
      doc.text(`${p}. Core Principles and Advanced Applications`, 20, y);
      y += 15;
      
      doc.setFontSize(11);
      doc.setTextColor(40, 40, 40);
      
      const para1 = `Understanding the fundamental paradigms of ${docTitle} is critical for any senior software engineer working with ${courseName}. In this chapter, we explore the theoretical underpinnings and practical implementation strategies that define modern architecture. The ecosystem has evolved significantly, introducing new patterns that optimize performance, maintainability, and scalability. `;
      const para2 = `A common pitfall for developers is neglecting the subtle lifecycle methods and memory management requirements inherent to this topic. By mastering these details, you can prevent insidious memory leaks and race conditions that plague enterprise applications. We recommend adopting a test-driven approach when integrating these components. `;
      const para3 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. `;
      
      const fullText = (para1 + para2 + para3).repeat(4);
      
      const lines = doc.splitTextToSize(fullText, 170);
      for (let i = 0; i < lines.length; i++) {
        if (y > pageHeight - 20) {
          doc.addPage();
          y = 20;
        }
        doc.text(lines[i], 20, y);
        y += 7;
      }
    }
    return doc;
  };

  const getOrGeneratePdfBase64 = async (docTitle: string): Promise<string | null> => {
    try {
      const safeTitle = docTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
      const pdfId = `${activeCourse?.id}_${safeTitle}`;
      const pdfRef = doc(db, 'course_pdfs', pdfId);
      const pdfSnap = await getDoc(pdfRef);
      
      if (pdfSnap.exists() && pdfSnap.data().base64) {
        return pdfSnap.data().base64;
      }
      
      // Yield to main thread so UI updates before massive sync operation
      await new Promise(r => setTimeout(r, 50));
      
      const docPdf = buildPDF(docTitle, activeCourse?.title || "Course");
      const base64Str = docPdf.output('datauristring');
      
      // Save asynchronously so we don't block returning
      setDoc(pdfRef, {
        courseId: activeCourse?.id,
        courseName: activeCourse?.title,
        title: docTitle,
        base64: base64Str,
        createdAt: new Date().toISOString()
      }).catch(e => console.error("Failed to save PDF to DB", e));
      
      return base64Str;
    } catch (e) {
      console.error(e);
      return null;
    }
  };

  const handleViewDoc = async (docTitle: string) => {
    setViewingDoc(docTitle);
    setIsGeneratingPdf(true);
    setPdfUrl(null);
    
    const base64Str = await getOrGeneratePdfBase64(docTitle);
    if (base64Str) setPdfUrl(base64Str);
    
    setIsGeneratingPdf(false);
  };

  const handleDownload = async (docTitle: string) => {
    setIsGeneratingPdf(true);
    const base64Str = await getOrGeneratePdfBase64(docTitle);
    setIsGeneratingPdf(false);
    
    if (base64Str) {
      const element = document.createElement("a");
      element.href = base64Str;
      element.download = `${docTitle.replace(/\s+/g, '_').toLowerCase()}.pdf`;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    }
  };

  const handleMarkComplete = async () => {
    if (!user || !activeCourse || !moduleData || isCompleted) return;
    try {
      const userRef = doc(db, 'users', user.uid);
      const currentCompleted = courseProgressData?.[activeCourse.id]?.completedWeeks || [];
      const newCompleted = Array.from(new Set([...currentCompleted, moduleData.week]));
      const isCourseFullyCompleted = newCompleted.length === activeCourse.syllabus.length;

      const userSnap = await getDoc(userRef);
      if (userSnap.exists()) {
        const userDataSnap = userSnap.data();
        const userCourses = userDataSnap.userCourses || [];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const courseIndex = userCourses.findIndex((c: any) => c.id === activeCourse.id);
        
        if (courseIndex > -1) {
          userCourses[courseIndex].completedWeeks = newCompleted;
          if (isCourseFullyCompleted) {
            userCourses[courseIndex].status = 'COMPLETED';
          }
        }
        
        const currentStats = userDataSnap.stats || { xp: 100, streak: 0, rank: 5000, lessonsCompleted: 0 };
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const updateData: any = {
          userCourses,
          stats: {
            ...currentStats,
            xp: (currentStats.xp || 100) + 50,
          }
        };

        if (isCourseFullyCompleted) {
          updateData.activeCourseId = null;
        }
        
        await updateDoc(userRef, updateData);
      }
      
      setIsCompleted(true);
      if (isCourseFullyCompleted) {
        alert(`Congratulations! You have completed the entire ${activeCourse.title} course!`);
      } else {
        alert(`Module ${moduleData.week} marked as complete!`);
      }
      if (activeCourse) {
        router.push(`/dashboard/courses/${encodeURIComponent(activeCourse.slug || activeCourse.id)}`);
      }
    } catch (e) {
      console.error("Error marking complete", e);
      alert("Failed to mark as complete");
    }
  };

  const handleMarkTopicComplete = async (topicName: string, e: React.MouseEvent) => {
    e.stopPropagation();
    if (!user || !activeCourse || !moduleData) return;
    try {
      const userRef = doc(db, 'users', user.uid);
      const currentCompletedTopics = courseProgressData?.[activeCourse.id]?.completedTopics || [];
      const topicId = `${moduleData.week}-${topicName}`;
      
      if (currentCompletedTopics.includes(topicId)) return;
      
      const newCompletedTopics = Array.from(new Set([...currentCompletedTopics, topicId]));
      
      setCourseProgressData({
         ...courseProgressData,
         [activeCourse.id]: {
            ...courseProgressData?.[activeCourse.id],
            completedTopics: newCompletedTopics
         }
      });
      
      const userSnap = await getDoc(userRef);
      if (userSnap.exists()) {
        const userDataSnap = userSnap.data();
        const userCourses = userDataSnap.userCourses || [];
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const courseIndex = userCourses.findIndex((c: any) => c.id === activeCourse.id);
        
        let isWeekFullyCompleted = false;
        let isCourseFullyCompleted = false;
        
        if (courseIndex > -1) {
          userCourses[courseIndex].completedTopics = newCompletedTopics;
          
          const allTopicsInWeekCompleted = moduleData.topics.every((t: string) => 
              newCompletedTopics.includes(`${moduleData.week}-${t}`)
          );
          
          if (allTopicsInWeekCompleted) {
             const currentCompletedWeeks = userCourses[courseIndex].completedWeeks || [];
             if (!currentCompletedWeeks.includes(moduleData.week)) {
                 const newCompletedWeeks = Array.from(new Set([...currentCompletedWeeks, moduleData.week]));
                 userCourses[courseIndex].completedWeeks = newCompletedWeeks;
                 isWeekFullyCompleted = true;
                 setIsCompleted(true);
                 
                 isCourseFullyCompleted = newCompletedWeeks.length === activeCourse.syllabus.length;
                 if (isCourseFullyCompleted) {
                     userCourses[courseIndex].status = 'COMPLETED';
                 }
             }
          }
        }
        
        const currentStats = userDataSnap.stats || { xp: 100, streak: 0, rank: 5000, lessonsCompleted: 0 };
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const updateData: any = {
          userCourses,
          stats: {
            ...currentStats,
            xp: (currentStats.xp || 100) + 10,
          }
        };

        if (isCourseFullyCompleted) {
          updateData.activeCourseId = null;
        }
        
        await updateDoc(userRef, updateData);
        
        if (isCourseFullyCompleted) {
            alert(`Congratulations! You have completed the entire ${activeCourse.title} course!`);
            router.push(`/dashboard/courses/${encodeURIComponent(activeCourse.slug || activeCourse.id)}`);
        } else if (isWeekFullyCompleted) {
            alert(`Module ${moduleData.week} marked as complete!`);
        }
      }
    } catch (e) {
      console.error("Error marking topic complete", e);
    }
  };


  useEffect(() => {
    if (loading || !userData || !user) return;
    
    let targetCourse: Course | null = null;
    for (const id in globalCourses) {
      const c = globalCourses[id];
      if (c.slug === courseSlug || c.id === courseSlug) {
        targetCourse = c;
        break;
      }
    }
    
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setActiveCourse(targetCourse);

    if (targetCourse) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const matchedCourse = userData.userCourses.find((c: any) => c.id === targetCourse!.id);
      if (matchedCourse) {
        setCourseProgressData({
          [targetCourse.id]: { 
            completedWeeks: matchedCourse.completedWeeks || [],
            completedTopics: matchedCourse.completedTopics || []
          }
        });
        
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const targetModule = targetCourse.syllabus.find((s: any) => (s.slug || s.id) === moduleSlug);
        if (targetModule && matchedCourse.completedWeeks?.includes(targetModule.week)) {
          setIsCompleted(true);
        } else {
          setIsCompleted(false);
        }
      }
    }
  }, [userData, globalCourses, loading, user, courseSlug, moduleSlug]);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const moduleData = activeCourse?.syllabus.find((s: any) => (s.slug || s.id) === moduleSlug);

  useEffect(() => {
    if (!moduleData || !activeCourse) return;
    
    const fetchVideo = async () => {
      try {
        const q = `${moduleData.title} ${activeCourse.language} tutorial`;
        const res = await fetch(`/api/youtube?q=${encodeURIComponent(q)}`);
        const json = await res.json();
        
        if (json.videoId) {
          setVideoId(json.videoId);
        } else {
          fallbackVideo();
        }
      } catch {
        fallbackVideo();
      }
    };
    
    const fallbackVideo = () => {
      const l = (activeCourse.language || "").toLowerCase();
      const t = (moduleData.title || "").toLowerCase();
      
      if (t.includes('advanced') || t.includes('expert')) setVideoId('mrmmEwW2n6g');
      else if (t.includes('interview') || t.includes('practice')) setVideoId('a_7Z7C_JCyo');
      else if (t.includes('project') || t.includes('build')) setVideoId('0riHps91AzE');
      else if (l.includes('python')) setVideoId('_uQrJ0TkZlc');
      else if (l.includes('javascript') || l.includes('js')) setVideoId('W6NZfCO5SIk');
      else if (l.includes('react')) setVideoId('Ke90Tje7VS0');
      else setVideoId('kqtD5dpn9C8');
    };
    
    fetchVideo();
  }, [moduleData, activeCourse]);

  const handleStartWorkspace = async () => {
    if (!user || !activeCourse || !moduleData) return;
    try {
      await setDoc(doc(db, 'users', user.uid), {
        workspaceSession: {
          title: `Week ${moduleData.week}: ${moduleData.title}`,
          language: activeCourse.language.toLowerCase(),
          code: ''
        }
      }, { merge: true });
      router.push('/dashboard/ai-workspace');
    } catch (e) {
      console.error("Failed to start module workspace", e);
    }
  };

  if (loading) {
    return (
      <div className="p-8 max-w-6xl mx-auto flex justify-center items-center h-64">
        <div className="w-8 h-8 border-4 border-indigo-500/30 border-t-indigo-500 rounded-full animate-spin"></div>
      </div>
    );
  }

  if (!activeCourse || !moduleData) {
    return (
      <div className="p-8 max-w-4xl mx-auto flex flex-col items-center justify-center h-[70vh] text-center">
        <h2 className="text-3xl font-bold text-white mb-4">Module Not Found</h2>
        <p className="text-slate-400 max-w-md mb-8">
          We couldn&apos;t find this module in your active course. Please go back to the course dashboard.
        </p>
        <Link 
          href="/dashboard/courses"
          className="px-8 py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-lg transition"
        >
          Back to Dashboard
        </Link>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-5xl mx-auto relative animate-in fade-in slide-in-from-bottom-4 duration-500">
      <Link href={`/dashboard/courses/${encodeURIComponent(courseSlug)}`} className="text-indigo-400 hover:text-indigo-300 font-medium text-sm flex items-center gap-2 mb-6 transition-colors w-max">
        ← Back to Course
      </Link>
      
      <div className="flex items-center gap-3 mb-3">
        <span className="bg-indigo-500/20 text-indigo-400 px-3 py-1 rounded-full text-xs font-bold tracking-wider">
          WEEK {moduleData.week}
        </span>
        <span className="text-slate-400 font-medium text-sm">{activeCourse.title}</span>
      </div>
      
      <h1 className="text-3xl md:text-4xl font-bold text-white mb-8">{moduleData.title}</h1>

      <div className="w-full aspect-video bg-slate-900 border border-slate-700 rounded-2xl mb-8 overflow-hidden shadow-2xl relative">
        {!videoId ? (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-4 text-indigo-400">
            <div className="w-12 h-12 border-4 border-indigo-500/30 border-t-indigo-500 rounded-full animate-spin"></div>
            <p className="font-medium animate-pulse">Finding the perfect video for &quot;{moduleData.title}&quot;...</p>
          </div>
        ) : (
          <iframe 
            className="w-full h-full relative z-10"
            src={`https://www.youtube.com/embed/${videoId}?autoplay=0&rel=0`}
            title={`${moduleData.title} Video Lecture`}
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
          ></iframe>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="md:col-span-2 space-y-6">
          <div className="bg-slate-800/40 border border-slate-700/50 p-6 rounded-xl">
            <h2 className="text-xl font-bold text-white mb-6 flex items-center gap-2">
              <span>📖</span> Reading Materials
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {moduleData.topics.map((topic: string, i: number) => {
                const topicId = `${moduleData.week}-${topic}`;
                const isTopicCompleted = (courseProgressData?.[activeCourse.id]?.completedTopics || []).includes(topicId);
                return (
                <div 
                  key={i} 
                  onClick={() => handleViewDoc(`${topic} Guide`)}
                  className={`flex items-center gap-3 p-4 border rounded-xl transition-colors cursor-pointer group shadow-sm ${isTopicCompleted ? 'bg-slate-900/50 border-emerald-500/30' : 'bg-slate-800/50 hover:bg-slate-800 border-slate-700/50'}`}
                >
                  <div className="text-3xl">{['📄', '📑', '📝', '📊'][i % 4]}</div>
                  <div className="flex-grow">
                    <h3 className={`font-medium text-sm transition-colors line-clamp-1 ${isTopicCompleted ? 'text-slate-400 line-through' : 'text-slate-200 group-hover:text-indigo-400'}`}>{topic} Guide</h3>
                    <p className="text-xs text-slate-500">PDF • {(i % 5) + 1}.{i % 9} MB</p>
                  </div>
                  <button 
                    onClick={(e) => handleMarkTopicComplete(topic, e)}
                    disabled={isTopicCompleted}
                    className={`p-2 rounded-full transition-colors flex items-center justify-center w-8 h-8 ${isTopicCompleted ? 'text-emerald-500 bg-emerald-500/10 cursor-not-allowed' : 'text-slate-500 group-hover:text-emerald-400 hover:bg-slate-700'}`}
                    title={isTopicCompleted ? "Completed" : "Mark Complete"}
                  >
                    {isTopicCompleted ? '✓' : '○'}
                  </button>
                  <button 
                    onClick={(e) => { e.stopPropagation(); handleDownload(`${topic} Guide`); }}
                    className="text-slate-500 group-hover:text-white transition-colors"
                  >
                    ↓
                  </button>
                </div>
              )})}
              
              <div 
                onClick={() => handleViewDoc(`Week ${moduleData.week} Cheatsheet`)}
                className="flex items-center gap-3 p-4 bg-indigo-900/20 hover:bg-indigo-900/40 border border-indigo-500/30 rounded-xl transition-colors cursor-pointer group shadow-sm"
              >
                <div className="text-3xl">🎯</div>
                <div className="flex-grow">
                  <h3 className="text-indigo-200 font-medium text-sm group-hover:text-white transition-colors line-clamp-1">Week {moduleData.week} Cheatsheet</h3>
                  <p className="text-xs text-indigo-400/70">Resource • 0.5 MB</p>
                </div>
                <button 
                  onClick={(e) => { e.stopPropagation(); handleDownload(`Week ${moduleData.week} Cheatsheet`); }}
                  className="text-indigo-400 group-hover:text-white transition-colors"
                >
                  ↓
                </button>
              </div>
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <div className="bg-gradient-to-br from-indigo-900/40 to-slate-900 border border-indigo-500/20 p-6 rounded-xl text-center">
            <div className="text-4xl mb-4">💻</div>
            <h3 className="text-lg font-bold text-white mb-2">Ready to practice?</h3>
            <p className="text-slate-400 text-sm mb-6">
              Apply what you&apos;ve learned in our interactive AI-powered coding environment.
            </p>
            <div className="space-y-3">
              <button 
                onClick={handleStartWorkspace}
                className="w-full py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-lg transition-colors shadow-lg shadow-indigo-500/20"
              >
                Practice in AI Workspace
              </button>
              
              <button 
                onClick={handleMarkComplete}
                disabled={isCompleted}
                className={`w-full py-3 font-bold rounded-lg transition-colors border shadow-lg flex items-center justify-center gap-2 ${
                  isCompleted 
                    ? 'bg-emerald-500/10 text-emerald-500 border-emerald-500/30 cursor-not-allowed shadow-none'
                    : 'bg-slate-800 hover:bg-slate-700 text-emerald-400 border-emerald-500/30 shadow-emerald-500/10'
                }`}
              >
                {isCompleted ? (
                  <><span>✓</span> Module Completed</>
                ) : (
                  <><span>✓</span> Mark Module as Complete</>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>

      {viewingDoc && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-5xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            <div className="p-4 border-b border-slate-800 flex justify-between items-center bg-slate-900">
              <h3 className="font-bold text-white flex items-center gap-2">📄 {viewingDoc}</h3>
              <button onClick={() => { setViewingDoc(null); setPdfUrl(null); }} className="text-slate-400 hover:text-white transition-colors w-8 h-8 flex items-center justify-center rounded-full hover:bg-slate-800">✕</button>
            </div>
            <div className="flex-1 w-full h-[70vh] bg-slate-950/50 relative flex items-center justify-center">
              {isGeneratingPdf ? (
                <div className="flex flex-col items-center gap-4 text-indigo-400">
                  <div className="w-12 h-12 border-4 border-indigo-500/30 border-t-indigo-500 rounded-full animate-spin"></div>
                  <p className="font-medium animate-pulse">Generating massive 27-page PDF document...</p>
                </div>
              ) : pdfUrl ? (
                <iframe 
                  src={pdfUrl} 
                  className="w-full h-full border-0" 
                  title={`Document Viewer - ${viewingDoc}`} 
                />
              ) : (
                <p className="text-slate-500">Failed to load PDF</p>
              )}
            </div>
            <div className="p-4 border-t border-slate-800 flex justify-end gap-3 bg-slate-900">
              <button onClick={() => { setViewingDoc(null); setPdfUrl(null); }} className="px-4 py-2 text-slate-300 hover:text-white transition">Close</button>
              <button 
                onClick={() => viewingDoc && handleDownload(viewingDoc)} 
                disabled={isGeneratingPdf}
                className={`px-4 py-2 rounded transition shadow ${isGeneratingPdf ? 'bg-indigo-600/50 text-indigo-200 cursor-not-allowed' : 'bg-indigo-600 hover:bg-indigo-500 text-white'}`}
              >
                Download PDF
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
