"use client";

import { useState, useEffect, Suspense, use } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Course } from '@/types/course';
import { downloadPDF } from "@/lib/generateCertificate";
import { useAuth } from '@/hooks/useAuth';
import { db, auth } from '@/lib/firebase';
import { doc, getDoc, updateDoc, setDoc } from "firebase/firestore";
import { useData } from '@/providers/DataProvider';
import { jsPDF } from "jspdf";

type Tab = 'syllabus' | 'documents' | 'user_study' | 'complement_course';

function DashboardContent({ courseSlug }: { courseSlug: string }) {
  const [activeTab, setActiveTab] = useState<Tab>('syllabus');
  const [viewingDoc, setViewingDoc] = useState<string | null>(null);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [viewingCaseStudy, setViewingCaseStudy] = useState<string | null>(null);
  const [activeCourse, setActiveCourse] = useState<Course | null>(null);

  const [courseProgress, setCourseProgress] = useState<Record<string, { completedWeeks: number[] }>>({});
  const { userData, globalCourses, loading: dataLoading } = useData();
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();

  const loading = dataLoading || authLoading;

  const buildPDF = (docTitle: string, courseName: string) => {
    const doc = new jsPDF();
    const pageHeight = doc.internal.pageSize.getHeight();
    let y = 20;

    // Title Page
    doc.setFontSize(28);
    doc.setTextColor(30, 64, 175);
    doc.text(docTitle, 20, y);
    y += 20;

    doc.setFontSize(16);
    doc.setTextColor(100, 100, 100);
    doc.text(`Comprehensive Reference Manual for ${courseName}`, 20, y);
    y += 30;

    doc.setFontSize(12);
    doc.setTextColor(60, 60, 60);
    doc.text(`Generated by CodeMentor AI`, 20, y);
    y += 20;

    // Table of Contents
    doc.addPage();
    y = 20;
    doc.setFontSize(22);
    doc.setTextColor(0, 0, 0);
    doc.text("Table of Contents", 20, y);
    y += 20;
    
    doc.setFontSize(12);
    for(let i=1; i<=25; i++) {
       doc.text(`${i}. Core Principles and Advanced Applications of ${docTitle.split(' ')[0]}`, 20, y);
       doc.text(`Page ${i + 2}`, 180, y, { align: 'right' });
       y += 10;
    }

    // Generate 25 pages of content
    for (let p = 1; p <= 25; p++) {
      doc.addPage();
      y = 20;
      doc.setFontSize(18);
      doc.setTextColor(30, 64, 175);
      doc.text(`${p}. Core Principles and Advanced Applications`, 20, y);
      y += 15;
      
      doc.setFontSize(11);
      doc.setTextColor(40, 40, 40);
      
      const para1 = `Understanding the fundamental paradigms of ${docTitle} is critical for any senior software engineer working with ${courseName}. In this chapter, we explore the theoretical underpinnings and practical implementation strategies that define modern architecture. The ecosystem has evolved significantly, introducing new patterns that optimize performance, maintainability, and scalability. `;
      const para2 = `A common pitfall for developers is neglecting the subtle lifecycle methods and memory management requirements inherent to this topic. By mastering these details, you can prevent insidious memory leaks and race conditions that plague enterprise applications. We recommend adopting a test-driven approach when integrating these components. `;
      const para3 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. `;
      
      const fullText = (para1 + para2 + para3).repeat(4);
      
      const lines = doc.splitTextToSize(fullText, 170);
      for (let i = 0; i < lines.length; i++) {
        if (y > pageHeight - 20) {
          doc.addPage();
          y = 20;
        }
        doc.text(lines[i], 20, y);
        y += 7;
      }
    }
    return doc;
  };

  const getOrGeneratePdfBase64 = async (docTitle: string): Promise<string | null> => {
    try {
      const safeTitle = docTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
      const pdfId = `${activeCourse?.id}_${safeTitle}`;
      const pdfRef = doc(db, 'course_pdfs', pdfId);
      const pdfSnap = await getDoc(pdfRef);
      
      if (pdfSnap.exists() && pdfSnap.data().base64) {
        return pdfSnap.data().base64;
      }
      
      await new Promise(r => setTimeout(r, 50));
      const docPdf = buildPDF(docTitle, activeCourse?.title || "Course");
      const base64Str = docPdf.output('datauristring');
      
      setDoc(pdfRef, {
        courseId: activeCourse?.id,
        courseName: activeCourse?.title,
        title: docTitle,
        base64: base64Str,
        createdAt: new Date().toISOString()
      }).catch(e => console.error("Failed to save PDF to DB", e));
      
      return base64Str;
    } catch (e) {
      console.error(e);
      return null;
    }
  };

  const handleViewDoc = async (docTitle: string) => {
    setViewingDoc(docTitle);
    setIsGeneratingPdf(true);
    setPdfUrl(null);
    
    const base64Str = await getOrGeneratePdfBase64(docTitle);
    if (base64Str) setPdfUrl(base64Str);
    
    setIsGeneratingPdf(false);
  };

  const handleDownload = async (docTitle: string) => {
    setIsGeneratingPdf(true);
    const base64Str = await getOrGeneratePdfBase64(docTitle);
    setIsGeneratingPdf(false);
    
    if (base64Str) {
      const element = document.createElement("a");
      element.href = base64Str;
      element.download = `${docTitle.replace(/\s+/g, '_').toLowerCase()}.pdf`;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    }
  };

  useEffect(() => {
    if (loading || !userData || !user) return;

    // Find target course from globalCourses based on slug or id
    let targetCourse: Course | null = null;
    for (const id in globalCourses) {
      const c = globalCourses[id];
      if (c.slug === courseSlug || c.id === courseSlug) {
        targetCourse = c;
        break;
      }
    }

    // eslint-disable-next-line react-hooks/set-state-in-effect
    setActiveCourse(targetCourse);

    if (targetCourse) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const matchedUserCourse = userData.userCourses.find((c: any) => c.id === targetCourse!.id);
      if (matchedUserCourse) {
        setCourseProgress({
          [targetCourse.id]: { completedWeeks: matchedUserCourse.completedWeeks || [] }
        });
        if (matchedUserCourse.score !== undefined) {
          setActiveCourse((prev) => prev ? { ...prev, score: matchedUserCourse.score } : prev);
        }
      } else {
        setCourseProgress({});
      }
    }
  }, [userData, globalCourses, loading, user, courseSlug]);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const handleStartModule = (week: any) => {
    if (!activeCourse) return;
    router.push(`/dashboard/module/${encodeURIComponent(activeCourse.slug || activeCourse.id)}/${week.slug || week.id}`);
  };

  // eslint-disable-next-line unused-imports/no-unused-vars
  const getYoutubeId = (lang: string) => {
    const l = lang.toLowerCase();
    if (l.includes('python')) return '_uQrJ0TkZlc';
    if (l.includes('javascript') || l.includes('js')) return 'W6NZfCO5SIk';
    if (l.includes('typescript')) return 'd56mG7DezGs';
    if (l.includes('react')) return 'Ke90Tje7VS0';
    if (l.includes('angular')) return '3qBXWUpoPHo';
    if (l.includes('vue')) return 'FXpIoQ_rT_c';
    if (l.includes('node') || l.includes('express')) return 'RLtyhwFtXQA';
    if (l.includes('mongo')) return 'ExcRbA7fy_A';
    if (l.includes('sql') || l.includes('postgres')) return 'HXV3zeQKqGY';
    if (l.includes('docker')) return '3c-iBn73dDE';
    if (l.includes('kubernetes') || l.includes('k8s')) return 'X48VuDVv0do';
    if (l.includes('aws') || l.includes('cloud')) return 'k1RI5locZE4';
    if (l.includes('c#') || l.includes('csharp')) return 'gfkTfcpWqAY';
    if (l.includes('c++') || l.includes('cpp')) return 'vLnPwxZdW4Y';
    if (l.includes('swift') || l.includes('ios')) return 'comQ1-x2a1Q';
    if (l.includes('kotlin') || l.includes('android')) return 'EExSSotojVI';
    if (l.includes('flutter') || l.includes('dart')) return 'VPvVD8t02U8';
    if (l.includes('go') || l.includes('golang')) return 'YS4e4q9oBaU';
    if (l.includes('rust')) return 'zF34dRivLOw';
    if (l.includes('java') || l.includes('spring')) return 'eIrMbAQSU34';
    if (l.includes('php') || l.includes('laravel')) return 'OK_JCtrrv-c';
    if (l.includes('ruby') || l.includes('rails')) return 'fmyvWz5TUWg';
    if (l.includes('django')) return 'F5mRW0jo-U4';
    if (l.includes('firebase')) return '9zdvDJGOMZ0';
    if (l.includes('graphql')) return 'ed8SzALpx1Q';
    if (l.includes('html') || l.includes('css')) return 'mU6anWqZJcc';
    return 'kqtD5dpn9C8';
  };

  const currentProgressPercent = activeCourse && courseProgress[activeCourse.id]
    ? Math.round(((courseProgress[activeCourse.id].completedWeeks?.length || 0) / (activeCourse.syllabus?.length || 1)) * 100)
    : 0;


  if (loading) {
    return (
      <div className="p-8 max-w-6xl mx-auto flex justify-center items-center h-64">
        <div className="w-8 h-8 border-4 border-indigo-500/30 border-t-indigo-500 rounded-full animate-spin"></div>
      </div>
    );
  }

  if (!activeCourse) {
    return (
      <div className="p-8 max-w-6xl mx-auto flex flex-col items-center justify-center h-[70vh] text-center">
        <div className="text-6xl mb-6">📚</div>
        <h2 className="text-3xl font-bold text-white mb-4">No Active Course</h2>
        <p className="text-slate-400 max-w-md mb-8">
          We couldn&apos;t find this course in your enrolled courses. Head over to the Course Catalog to enroll!
        </p>
        <Link
          href="/courses"
          className="px-8 py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-bold rounded-lg transition shadow-lg shadow-indigo-500/20"
        >
          Browse Catalog
        </Link>
      </div>
    );
  }

  // Calculate dynamic progress
  const completedWeeks = activeCourse && courseProgress[activeCourse.id] ? (courseProgress[activeCourse.id].completedWeeks || []) : [];
  const completedCount = completedWeeks.length;
  const totalWeeks = activeCourse.syllabus?.length || 0;
  const progressPercent = totalWeeks === 0 ? 0 : Math.round((completedCount / totalWeeks) * 100);

  // Determine current active week (first uncompleted week, defaults to week 1, capped at totalWeeks)
  let currentWeek = 1;
  for (let i = 0; i < totalWeeks; i++) {
    if (!completedWeeks.includes(activeCourse.syllabus[i].week)) {
      currentWeek = activeCourse.syllabus[i].week;
      break;
    }
    if (i === totalWeeks - 1) currentWeek = totalWeeks;
  }

  return (
    <div className="p-8 max-w-7xl mx-auto relative flex flex-col lg:flex-row gap-8">
      {/* Main Course Content */}
      <div className="flex-grow min-w-0">
        {/* Modals */}
        {viewingDoc && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
            <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-5xl max-h-[90vh] flex flex-col shadow-2xl relative animate-in fade-in zoom-in-95 duration-200">
              <div className="p-4 border-b border-slate-800 flex justify-between items-center">
                <h3 className="font-bold text-white flex items-center gap-2">📄 {viewingDoc}</h3>
                <button onClick={() => { setViewingDoc(null); setPdfUrl(null); }} className="text-slate-400 hover:text-white transition-colors w-8 h-8 flex items-center justify-center rounded-full hover:bg-slate-800">✕</button>
              </div>
              <div className="flex-1 w-full h-[70vh] bg-slate-950/50 relative flex items-center justify-center">
                {isGeneratingPdf ? (
                  <div className="flex flex-col items-center gap-4 text-indigo-400">
                    <div className="w-12 h-12 border-4 border-indigo-500/30 border-t-indigo-500 rounded-full animate-spin"></div>
                    <p className="font-medium animate-pulse">Generating massive 27-page PDF document...</p>
                  </div>
                ) : pdfUrl ? (
                  <iframe 
                    src={pdfUrl} 
                    className="w-full h-full border-0" 
                    title={`Document Viewer - ${viewingDoc}`} 
                  />
                ) : (
                  <p className="text-slate-500">Failed to load PDF</p>
                )}
              </div>
              <div className="p-4 border-t border-slate-800 flex justify-end gap-3">
                <button onClick={() => { setViewingDoc(null); setPdfUrl(null); }} className="px-4 py-2 text-slate-300 hover:text-white transition">Close</button>
                <button 
                  onClick={() => viewingDoc && handleDownload(viewingDoc)} 
                  disabled={isGeneratingPdf}
                  className={`px-4 py-2 rounded transition shadow ${isGeneratingPdf ? 'bg-indigo-600/50 text-indigo-200 cursor-not-allowed' : 'bg-indigo-600 hover:bg-indigo-500 text-white'}`}
                >
                  Download PDF
                </button>
              </div>
            </div>
          </div>
        )}

        {viewingCaseStudy && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
            <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-3xl max-h-[85vh] flex flex-col shadow-2xl relative animate-in fade-in zoom-in-95 duration-200">
              <div className="p-6 border-b border-slate-800 flex justify-between items-center">
                <h3 className="text-xl font-bold text-white">Case Study: {viewingCaseStudy}</h3>
                <button onClick={() => setViewingCaseStudy(null)} className="text-slate-400 hover:text-white transition-colors w-8 h-8 flex items-center justify-center rounded-full hover:bg-slate-800">✕</button>
              </div>
              <div className="p-8 overflow-y-auto custom-scrollbar flex-1 space-y-6 text-slate-300 leading-relaxed">
                <p><strong>Abstract:</strong> This case study explores how a top-tier tech company optimized their infrastructure and reduced technical debt by 40% using advanced {activeCourse?.language || "programming"} patterns. We will analyze their architecture choices and implementation challenges.</p>

                <h4 className="text-lg font-bold text-slate-200 mt-8 mb-4 border-b border-slate-800 pb-2">1. The Problem Space</h4>
                <p>In early 2024, the engineering team noticed that their legacy monolithic backend was causing significant latency issues during peak traffic. This led to customer dissatisfaction and increased support ticket volumes.</p>

                <h4 className="text-lg font-bold text-slate-200 mt-8 mb-4 border-b border-slate-800 pb-2">2. Architecture Decisions</h4>
                <p>Instead of relying on vertical scaling, the team implemented a modern architecture using {activeCourse?.language || "the latest standards"}. They containerized their workloads and implemented strict type safety and design patterns.</p>

                <h4 className="text-lg font-bold text-slate-200 mt-8 mb-4 border-b border-slate-800 pb-2">3. Implementation Guardrails</h4>
                <p>They wrapped the core deployment step with automated CI/CD pipelines. If the evaluator determined that the primary build contained memory leaks or unhandled exceptions in {activeCourse?.language || "the codebase"}, the deployment was blocked and a fallback was triggered.</p>

                <div className="bg-indigo-500/10 border border-indigo-500/30 p-4 rounded-xl mt-8">
                  <p className="text-indigo-200 font-medium">Key Takeaway: Modern design patterns combined with {activeCourse?.language || "strict"} guardrails provide the most robust defense against enterprise system failures.</p>
                </div>
              </div>
              <div className="p-6 border-t border-slate-800 flex justify-between items-center bg-slate-900 rounded-b-2xl">
                <span className="text-sm text-slate-500">Estimated read time: 5 mins</span>
                <button onClick={() => setViewingCaseStudy(null)} className="px-6 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition shadow font-medium">Mark as Read</button>
              </div>
            </div>
          </div>
        )}

        {/* Course Header */}
        <div className="mb-8">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <span className="bg-indigo-500/20 text-indigo-400 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">
                Active Course
              </span>
              <span className="text-slate-400 text-sm">Module {currentWeek} of {totalWeeks}</span>
            </div>
            <Link
              href="/dashboard/courses"
              className="text-sm font-medium text-slate-300 hover:text-white transition-colors bg-slate-800/80 hover:bg-slate-700 px-4 py-2 rounded-lg flex items-center gap-2 border border-slate-700"
            >
              ← Back to Courses
            </Link>
          </div>
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-4">
            <h1 className="text-3xl font-bold text-white">{activeCourse.title}</h1>
            {currentProgressPercent === 100 && (
              <div className="flex gap-3">
                {activeCourse.score !== undefined && activeCourse.score >= 75 ? (
                  <button
                    onClick={() => {
                      const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
                      downloadPDF(activeCourse.title, user?.displayName || "Developer", date);
                    }}
                    className="px-6 py-2 bg-gradient-to-r from-emerald-500 to-emerald-600 hover:from-emerald-400 hover:to-emerald-500 text-white font-bold rounded-lg shadow-lg shadow-emerald-500/20 transition-all flex items-center gap-2"
                  >
                    <span className="text-xl">🎓</span> Download Certificate
                  </button>
                ) : (
                  <Link
                    href={`/dashboard/history/${encodeURIComponent(activeCourse.slug || activeCourse.id)}/test`}
                    className="px-6 py-2 bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-400 hover:to-purple-500 text-white font-bold rounded-lg shadow-lg shadow-indigo-500/20 transition-all flex items-center gap-2"
                  >
                    <span className="text-xl">📝</span> Take Final Test
                  </Link>
                )}
              </div>
            )}
          </div>

          <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-md">
            <div className="flex justify-between text-sm mb-2">
              <span className="text-slate-300 font-medium">Course Progress</span>
              <span className="text-indigo-400 font-bold">{progressPercent}%</span>
            </div>
            <div className="w-full h-3 bg-slate-800 rounded-full overflow-hidden">
              <div className="h-full bg-indigo-500 rounded-full transition-all duration-500" style={{ width: `${progressPercent}%` }}></div>
            </div>
          </div>
        </div>

        {/* Tabs Navigation */}
        <div className="flex gap-2 border-b border-slate-800 mb-6 overflow-x-auto custom-scrollbar">
          <button
            onClick={() => setActiveTab('syllabus')}
            className={`px-6 py-3 font-medium transition-colors border-b-2 whitespace-nowrap ${activeTab === 'syllabus'
                ? 'border-indigo-500 text-indigo-400'
                : 'border-transparent text-slate-400 hover:text-slate-200 hover:border-slate-600'
              }`}
          >
            📅 Weekly Plan
          </button>
          <button
            onClick={() => setActiveTab('documents')}
            className={`px-6 py-3 font-medium transition-colors border-b-2 whitespace-nowrap ${activeTab === 'documents'
                ? 'border-indigo-500 text-indigo-400'
                : 'border-transparent text-slate-400 hover:text-slate-200 hover:border-slate-600'
              }`}
          >
            📄 Documents
          </button>
          <button
            onClick={() => setActiveTab('user_study')}
            className={`px-6 py-3 font-medium transition-colors border-b-2 whitespace-nowrap ${activeTab === 'user_study'
                ? 'border-indigo-500 text-indigo-400'
                : 'border-transparent text-slate-400 hover:text-slate-200 hover:border-slate-600'
              }`}
          >
            👥 User Study
          </button>
          <button
            onClick={() => setActiveTab('complement_course')}
            className={`px-6 py-3 font-medium transition-colors border-b-2 whitespace-nowrap ${activeTab === 'complement_course'
                ? 'border-indigo-500 text-indigo-400'
                : 'border-transparent text-slate-400 hover:text-slate-200 hover:border-slate-600'
              }`}
          >
            🔗 Complement Course
          </button>
        </div>

        {/* Tab Content */}
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 min-h-[400px]">

          {/* Syllabus Tab */}
          {activeTab === 'syllabus' && (
            <div className="animate-in fade-in slide-in-from-bottom-2 duration-300">
              <h2 className="text-xl font-bold text-white mb-6">Course Syllabus</h2>
              {(!activeCourse.syllabus || activeCourse.syllabus.length === 0) ? (
                <div className="text-slate-400 py-8 text-center">
                  This course currently has no syllabus modules available.
                </div>
              ) : (
                <div className="space-y-4">
                  {activeCourse.syllabus.map((week) => {
                    const isCompleted = completedWeeks.includes(week.week);
                    const isCurrent = week.week === currentWeek && !isCompleted;

                    return (
                      <div key={week.week} className={`border rounded-xl p-5 transition-colors flex flex-col md:flex-row md:items-center justify-between gap-4 ${isCompleted ? 'bg-slate-900/50 border-emerald-500/30' :
                          isCurrent ? 'bg-indigo-900/10 border-indigo-500/50 shadow-[0_0_15px_rgba(99,102,241,0.1)]' :
                            'bg-slate-800/50 border-slate-700/50 hover:border-slate-600'
                        }`}>
                        <div>
                          <div className="flex items-center gap-4 mb-3">
                            <div className={`font-bold w-10 h-10 flex items-center justify-center rounded-lg ${isCompleted ? 'bg-emerald-500/20 text-emerald-400' :
                                isCurrent ? 'bg-indigo-500/20 text-indigo-400' :
                                  'bg-slate-700 text-slate-400'
                              }`}>
                              {isCompleted ? '✓' : `W${week.week}`}
                            </div>
                            <h3 className={`text-lg font-bold ${isCompleted ? 'text-slate-400 line-through' : 'text-slate-200'}`}>
                              {week.title}
                            </h3>
                          </div>
                          <ul className={`list-none text-sm ml-14 space-y-2 ${isCompleted ? 'text-slate-500' : 'text-slate-400'}`}>
                            {week.topics.map((topic, i) => (
                              <li key={i} className="flex items-center gap-2">
                                <span className="text-indigo-500">•</span>
                                <button
                                  onClick={(e) => { e.stopPropagation(); handleViewDoc(topic); }}
                                  className="hover:text-indigo-400 hover:underline transition-colors text-left"
                                >
                                  {topic}
                                </button>
                              </li>
                            ))}
                          </ul>
                        </div>
                        <div className="flex gap-2 md:self-end">
                          <button
                            onClick={() => handleStartModule(week)}
                            disabled={isCompleted}
                            className={`px-6 py-2.5 font-medium rounded-lg transition-colors border whitespace-nowrap ${isCompleted ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-500 cursor-not-allowed' :
                                isCurrent ? 'bg-indigo-600 text-white border-indigo-500 hover:bg-indigo-500 shadow-lg shadow-indigo-500/20' :
                                  'bg-indigo-600/20 text-indigo-400 hover:bg-indigo-600 hover:text-white border-indigo-500/30'
                              }`}
                          >
                            {isCompleted ? 'Completed ✓' : isCurrent ? 'Continue Module' : 'Start Module'}
                          </button>
                          {!isCompleted && (
                            <button
                              onClick={async () => {
                                const userAuth = auth.currentUser;
                                if (!userAuth || !activeCourse) return;
                                try {
                                  const userRef = doc(db, 'users', userAuth.uid);
                                  const userSnap = await getDoc(userRef);
                                  if (userSnap.exists()) {
                                    const userData = userSnap.data();
                                    const userCourses = userData.userCourses || [];
                                    // eslint-disable-next-line @typescript-eslint/no-explicit-any
                                    const courseIndex = userCourses.findIndex((c: any) => c.id === activeCourse.id);

                                    if (courseIndex > -1) {
                                      const cWeeks = userCourses[courseIndex].completedWeeks || [];
                                      const newWeeks = Array.from(new Set([...cWeeks, week.week]));
                                      userCourses[courseIndex].completedWeeks = newWeeks;

                                      if (newWeeks.length >= (activeCourse.syllabus?.length || 0)) {
                                        userCourses[courseIndex].status = 'COMPLETED';
                                      }

                                      await updateDoc(userRef, { userCourses });
                                    }
                                  }
                                } catch (e) {
                                  console.error(e);
                                }
                              }}
                              className="px-4 py-2.5 font-medium rounded-lg transition-colors border whitespace-nowrap bg-emerald-600/20 text-emerald-400 hover:bg-emerald-600 hover:text-white border-emerald-500/30 text-xs flex items-center"
                            >
                              Test: Mark Done
                            </button>
                          )}
                        </div>
                      </div>
                    )
                  })}
                </div>
              )}
            </div>
          )}

          {/* Documents Tab */}
          {activeTab === 'documents' && (
            <div className="animate-in fade-in slide-in-from-bottom-2 duration-300">
              <h2 className="text-xl font-bold text-white mb-6">Course Documents & Resources</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {(activeCourse.documents || []).map((doc, i) => (
                  <div key={i} onClick={() => handleViewDoc(doc.title)} className="p-4 bg-slate-800/50 hover:bg-slate-800 border border-slate-700/50 rounded-xl transition-all cursor-pointer group flex items-start gap-4 hover:border-indigo-500/50 shadow-sm">
                    <div className="text-4xl group-hover:scale-110 transition-transform">{doc.icon}</div>
                    <div className="flex-grow">
                      <h4 className="font-bold text-slate-200 group-hover:text-indigo-400 transition-colors mb-1">{doc.title}</h4>
                      <div className="flex items-center gap-3 text-xs text-slate-500">
                        <span className="bg-slate-900 px-2 py-0.5 rounded text-slate-400">PDF</span>
                        <span>{doc.size}</span>
                      </div>
                    </div>
                    <button
                      onClick={(e) => { e.stopPropagation(); handleDownload(doc.title); }}
                      className="p-2 text-slate-400 hover:text-indigo-400 bg-slate-900 rounded-full transition-colors"
                    >
                      ↓
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* User Study Tab */}
          {activeTab === 'user_study' && (
            <div className="animate-in fade-in slide-in-from-bottom-2 duration-300">
              <h2 className="text-xl font-bold text-white mb-6">User Studies & Case Scenarios</h2>
              <div className="space-y-6">
                <div className="bg-slate-800/30 p-6 border border-slate-700 rounded-xl">
                  <div className="flex justify-between items-start mb-4">
                    <h3 className="text-lg font-bold text-slate-200">Case Study: Enterprise Migration to {activeCourse?.language || "Modern Stack"}</h3>
                    <span className="bg-emerald-500/20 text-emerald-400 text-xs px-2 py-1 rounded font-medium">Required Reading</span>
                  </div>
                  <p className="text-slate-400 text-sm mb-4 leading-relaxed">
                    Explore how a top-tier tech company optimized their infrastructure by 40% using advanced {activeCourse?.language || "programming"} patterns. Analyze their architecture choices and implementation challenges.
                  </p>
                  <button
                    onClick={() => setViewingCaseStudy(`Enterprise Migration to ${activeCourse?.language || "Modern Stack"}`)}
                    className="text-indigo-400 text-sm font-medium hover:text-indigo-300 transition-colors"
                  >
                    Read Case Study →
                  </button>
                </div>

                <div className="bg-slate-800/30 p-6 border border-slate-700 rounded-xl opacity-75 hover:opacity-100 transition-opacity">
                  <div className="flex justify-between items-start mb-4">
                    <h3 className="text-lg font-bold text-slate-200">Interactive Scenario: Designing a {activeCourse?.language || "Backend"} System</h3>
                    <span className="bg-slate-700 text-slate-300 text-xs px-2 py-1 rounded font-medium">Optional Practice</span>
                  </div>
                  <p className="text-slate-400 text-sm mb-4 leading-relaxed">
                    Step into the role of a senior engineer and design the architecture for a scalable {activeCourse?.language || ""} application. You will be evaluated on latency, security, and scalability.
                  </p>
                  <button
                    onClick={() => {
                      localStorage.setItem('workspace_initial_title', `Interactive Scenario: ${activeCourse?.language || "Backend"} System`);
                      localStorage.setItem('workspace_initial_language', activeCourse?.language?.toLowerCase() || 'javascript');
                      router.push('/dashboard/ai-workspace');
                    }}
                    className="text-indigo-400 text-sm font-medium hover:text-indigo-300 transition-colors"
                  >
                    Start Scenario →
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Complement Course Tab */}
          {activeTab === 'complement_course' && (
            <div className="animate-in fade-in slide-in-from-bottom-2 duration-300">
              <h2 className="text-xl font-bold text-white mb-6">Recommended Complementary Content</h2>
              <p className="text-slate-400 mb-6">Enhance your learning with these hand-picked external resources that complement this week&apos;s module.</p>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {(activeCourse.videos || []).map((item, i) => (
                  <a
                    key={i}
                    href={item.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className={`bg-gradient-to-br ${item.color} border border-slate-700/50 p-5 rounded-xl flex flex-col h-full hover:border-slate-500 transition-colors cursor-pointer block`}
                  >
                    <div className="text-3xl mb-4">{item.icon}</div>
                    <h3 className="text-slate-200 font-bold mb-2 flex-grow">{item.title}</h3>
                    <div className="text-xs text-slate-400 flex justify-between items-center mt-4 pt-4 border-t border-slate-700/50">
                      <span>{item.author}</span>
                      <span className="bg-slate-900/50 px-2 py-1 rounded">{item.duration}</span>
                    </div>
                  </a>
                ))}
              </div>
            </div>
          )}

        </div>
      </div>
    </div>
  );
}

export default function DashboardCourseDetailsPage({ params }: { params: Promise<{ courseSlug: string }> }) {
  const unwrappedParams = use(params);
  return (
    <Suspense fallback={
      <div className="p-8 max-w-6xl mx-auto flex justify-center items-center h-64">
        <div className="w-8 h-8 border-4 border-indigo-500/30 border-t-indigo-500 rounded-full animate-spin"></div>
      </div>
    }>
      <DashboardContent courseSlug={unwrappedParams.courseSlug} />
    </Suspense>
  );
}
